### ISSUE TITLE
github install fails

### ISSUE THREAD

**Issue by J0vid** [hlorenzo/ddsPLS#1]
I was trying to install from github using devtools (devtools::install_github("hlorenzo/ddsPLS")) and get the following error that causes the package installation to fail: 

Error in parse(outFile) : 
  /tmp/RtmphWkpvT/devtools21e3504c6f4e/hlorenzo-ddsPLS-2235989/R/summary.perf_mddsPLS.R:133:0: unexpected end of input
131:   }
132: }
    ^
ERROR: unable to collate and parse R files for package ‘ddsPLS’

Any thoughts?

**Comment by hlorenzo** [comment]
Hello J0vid,
A typo made its own way to the code. It might be fixed now.
Bests,
Hadrien

**Comment by J0vid** [comment]
Thanks, that solved the problem!
