### ISSUE TITLE
Return optimal combination in perf_mddsPLS

### ISSUE THREAD

**Issue by jonas-hag** [hlorenzo/ddsPLS#4]
It would be great if you could include the optimal combination of hyperparameters (R/L0/lambda) found during the CV in the return values of `perf_mddsPLS` or provide a function to extract these values.

**Comment by jonas-hag** [comment]
I've written a short function, but only tested for regression models, maybe you can add something like this:

```
#' Extract the optimal combination of hyperparamters from perf_mddsPLS
#'
#' @param object model of class perf_mddsPLS
#' @param type which measure should be used, so far only RMSEP supported
#'
#' @return
#' @export
#'
#' @importFrom checkmate assert_class
extract_optimal_parameters <- function(object,
                                       type = "RMSEP") {
  assert_class(object, "perf_mddsPLS")
  type <- match.arg(type)

  # extract the mean RMSEP values
  values <- cbind(object$RMSEP[ , 1:2],
                  rowMeans(object$RMSEP[ , -(1:2)]))
  colnames(values)[3] <- "mean_RMSEP"

  # get the minimum mean RMSEP value
  index_min <- which.min(values[, 3])
  min_val <- values[index_min, ]

  # prepare the return value
  if (colnames(values)[2] == "Lambdas") {
    res <- list(R = min_val$R,
                lambda = min_val$Lambdas,
                mean_RMSEP = min_val$mean_RMSEP)
  } else {
    res <- list(R = min_val$R,
                L0 = min_val$L0,
                mean_RMSEP = min_val$mean_RMSEP)
  }
  res

}
```

**Comment by hlorenzo** [comment]
Thank you jonas-hag for your input
Ther is a critical question about the selection of the best model in multivariate response prediction.
I already proposed two candidates for this operation and they are accessible in the object `Optim`, an output of the function `perf_mddsPLS`. The two candidates are
- "optim_para_all"
The couple for which the mean of the cross-validated errors is extremum (minimum in the regression case and maximum in the classification case) along the q response variables.
- "optim_para_one"
The couple for which the extremum (minimum in the regression case and maximum in the classification case) value over all the cross-validated errors is reached along the q response variables.
The outputs of that function were badly detailed and did work badly for more than one value for `R`. It should be fixed now
Thank you again for your kind input
